const countryData = new Map([
    ["ag", "Antigua and Barbuda"],
    ["ar", "Argentina"],
    ["aw", "Aruba"],
    ["bb", "Barbados"],
    ["bz", "Belize"],
    ["bo", "Bolivia"],
    ["br", "Brazil"],
    ["ca", "Canada"],
    ["cl", "Chile"],
    ["co", "Colombia"],
    ["cr", "Costa Rica"],
    ["cu", "Cuba"],
    ["cw", "Curacao"],
    ["dm", "Dominica"],
    ["do", "Dominican Republic"],
    ["ec", "Ecuador"],
    ["sv", "El Salvador"],
    ["fk", "Falkland Islands"],
    ["gd", "Grenada"],
    ["gt", "Guatemala"],
    ["gy", "Guyana"],
    ["ht", "Haiti"],
    ["hn", "Honduras"],
    ["jm", "Jamaica"],
    ["ky", "Cayman Islands"],
    ["lc", "Saint Lucia"],
    ["mx", "Mexico"],
    ["ms", "Montserrat"],
    ["ni", "Nicaragua"],
    ["pa", "Panama"],
    ["pe", "Peru"],
    ["pr", "Puerto Rico"],
    ["py", "Paraguay"],
    ["sr", "Suriname"],
    ["tt", "Trinidad and Tobago"],
    ["us", "United States"],
    ["uy", "Uruguay"],
    ["ve", "Venezuela"],
    ["vg", "British Virgin Islands"],
    ["vi", "American Virgin Islands"]
]);