const countryData = new Map([
    ["af", "Afghanistan"],
    ["bh", "Bahrain"],
    ["bd", "Bangladesh"],
    ["bn", "Brunei"],
    ["bt", "Bhutan"],
    ["kh", "Cambodia"],
    ["cn", "China"],
    ["cx", "Christmas Island"],
    ["cc", "Cocos Islands"],
    ["ge", "Georgia"],
    ["hk", "Hong Kong"],
    ["in", "India"],
    ["id", "Indonesia"],
    ["ir", "Iran"],
    ["iq", "Iraq"],
    ["il", "Israel"],
    ["jp", "Japan"],
    ["jo", "Jordan"],
    ["kz", "Kazakhstan"],
    ["kw", "Kuwait"],
    ["kg", "Kyrgyzstan"],
    ["la", "Laos"],
    ["lb", "Lebanon"],
    ["mo", "Macau"],
    ["my", "Malaysia"],
    ["mv", "Maldives"],
    ["mn", "Mongolia"],
    ["mm", "Myanmar"],
    ["np", "Nepal"],
    ["kp", "North Korea"],
    ["mk", "North Macedonia"],
    ["om", "Oman"],
    ["pk", "Pakistan"],
    ["pw", "Palau"],
    ["ph", "Philippines"],
    ["qa", "Qatar"],
    ["st", "Saudi Arabia"],
    ["sg", "Singapore"],
    ["kr", "South Korea"],
    ["lk", "Sri Lanka"],
    ["sy", "Syria"],
    ["tw", "Taiwan"],
    ["tj", "Tajikistan"],
    ["th", "Thailand"],
    ["tl", "Timor-Leste"],
    ["tm", "Turkmenistan"],
    ["ae", "United Arab Emirates"],
    ["uz", "Uzbekistan"],
    ["vn", "Vietnam"],
    ["ye", "Yemen"]
]);