const countryData = new Map([
    ["al", "Albania"],
    ["ad", "Andorra"],
    ["at", "Austria"],
    ["by", "Belarus"],
    ["be", "Belgium"],
    ["ba", "Bosnia and Herzegovina"],
    ["bg", "Bulgaria"],
    ["hr", "Croatia"],
    ["cy", "Cyprus"],
    ["cz", "Czech Republic"],
    ["dk", "Denmark"],
    ["ee", "Estonia"],
    ["fo", "Faroe Islands"],
    ["fi", "Finland"],
    ["fr", "France"],
    ["ge", "Georgia"],
    ["de", "Germany"],
    ["gi", "Gibraltar"],
    ["gr", "Greece"],
    ["gg", "Guernsey"],
    ["hu", "Hungary"],
    ["is", "Iceland"],
    ["ie", "Ireland"],
    ["im", "Isle of Man"],
    ["it", "Italy"],
    ["je", "Jersey"],
    ["lv", "Latvia"],
    ["li", "Liechtenstein"],
    ["lt", "Lithuania"],
    ["lu", "Luxembourg"],
    ["md", "Moldova"],
    ["mc", "Monaco"],
    ["me", "Montenegro"],
    ["nl", "Netherlands"],
    ["mk", "North Macedonia"],
    ["no", "Norway"],
    ["pl", "Poland"],
    ["pt", "Portugal"],
    ["ro", "Romania"],
    ["ru", "Russia"],
    ["sm", "San Marino"],
    ["rs", "Serbia"],
    ["sk", "Slovakia"],
    ["si", "Slovenia"],
    ["es", "Spain"],
    ["se", "Sweden"],
    ["ch", "Switzerland"],
    ["tr", "Turkiye"],
    ["ua", "Ukraine"],
    ["gb", "United Kingdom"],
    ["va", "Vatican City"]
]);