const countryData = new Map([
    ["as", "American Samoa"],
    ["au", "Australia"],
    ["ck", "Cook Islands"],
    ["fm", "Micronesia"],
    ["fj", "Fiji"],
    ["gu", "Guam"],
    ["ki", "Kiribati"],
    ["mh", "Marshall Islands"],
    ["nr", "Nauru"],
    ["nc", "New Caledonia"],
    ["nz", "New Zealand"],
    ["nu", "Niue"],
    ["nf", "Norfolk Island"],
    ["mp", "Northern Mariana Islands"],
    ["pw", "Palau"],
    ["pg", "Papua New Guinea"],
    ["pn", "Pitcairn"],
    ["sb", "Solomon Islands"],
    ["to", "Tonga"],
    ["tv", "Tuvalu"],
    ["vu", "Vanuatu"],
    ["ws", "Samoa"]
]);
